### ISSUE TITLE
The problem of training

### ISSUE THREAD

**Issue by ThoamsDong** [naoto0804/cross-domain-detection#10]
Thanks for your work !!! When I tried to train the model using _"python train_model.py --root datasets/clipart --subset train --result result --det_type ssd300 --data_type clipart --gpu 0"_, it worked only 16 epoches by Titan XP. Do you have any advice?
![捕获](https://user-images.githubusercontent.com/34698969/58452269-5890ef80-8149-11e9-9b72-ca63355318f3.PNG)

**Comment by naoto0804** [comment]
I haven't faced that issue.. Do you still face the same issue?
