### ISSUE TITLE
Training with own dataset.

### ISSUE THREAD

**Issue by monjurulkarim** [naoto0804/cross-domain-detection#12]
Hi, Thanks for the amazing paper and this repository.
I am trying to implement this repository with my own dataset. I have a different number of classes. Can you give me any idea how can I do that?

**Comment by naoto0804** [comment]
Note that the classed to be detected in the target domain is a subset of a pre-trained object detector. In our paper, I used VOC2007-12 pre-trained model (20 classes).

To fully use the power of pre-trained detector, we didn't modify the network and train the model (in watercolor and comic setting, the dataset only contains 6 class). During training, if there's no instance for a class, the model will (hopefully) less likely predict it.
