### ISSUE TITLE
code for getting the DT data

### ISSUE THREAD

**Issue by liye228** [naoto0804/cross-domain-detection#13]
@naoto0804 hello!

Thanks for your contribution!
Can you provide the code about using the cycleGAN  to get the (VOC) DT data ?

Thank you!

**Comment by naoto0804** [comment]
Please refer to the [original implmentation](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix). If you want to reproduce my result, please follow `datasets/prepare_dt.sh` to download the generated images.
