### ISSUE TITLE
when i use the download.sh to download your trained model i failed  the things i get is about 256bite and i can not extract 

### ISSUE THREAD

**Issue by dyx118186878** [naoto0804/cross-domain-detection#17]

**Comment by naoto0804** [comment]
Unfortunately, the server is down temporarily. Could you download all the data from here?
https://drive.google.com/open?id=1DLepaCe7ndrqVU3D8x7yjN3TMfhZXSCV

**Comment by dyx118186878** [comment]
thanks a lot , but when i connect the wed , i donot have the permission ,i  request access  and wait the emai . my google account  is sgsj2191252434@gmail.com   by the way i met the same problem when i download the datasets, can you help me? I would appreciate it.

**Comment by naoto0804** [comment]
Now it should be viewed by anyone who knows the link above, could you try again?

**Comment by dyx118186878** [comment]
yes  i see them  thanks a lot
