### ISSUE TITLE
Can't download the datasets using bash prepare.sh

### ISSUE THREAD

**Issue by czzbb** [naoto0804/cross-domain-detection#18]
Thanks for you job first! Can't download the datasets using bash prepare.sh. Is any problem with the link or file?

**Comment by czzbb** [comment]
.

**Comment by Zxr1314** [comment]
Me too

**Comment by naoto0804** [comment]
Unfortunately, the server is down temporarily. Could you download all the data from here?
https://drive.google.com/open?id=1DLepaCe7ndrqVU3D8x7yjN3TMfhZXSCV

**Comment by 1184125805** [comment]
This page cannot open T...T

**Comment by naoto0804** [comment]
Since the server is not down now, please run `prepare.sh`
