### ISSUE TITLE
Please grant permisson to access http://www.hal.t.u-tokyo.ac.jp/~inoue/projects/cross_domain_detection/

### ISSUE THREAD

**Issue by pnhaison** [naoto0804/cross-domain-detection#19]
I cannot download dataset ,pretrained model using bash .Please grant permission !

**Comment by naoto0804** [comment]
Unfortunately, the server is down temporarily, I'll make sure to let you know when it's back.

**Comment by naoto0804** [comment]
Could you download all the data from here?
https://drive.google.com/open?id=1DLepaCe7ndrqVU3D8x7yjN3TMfhZXSCV

**Comment by Zxr1314** [comment]
> Could you download all the data from here?
> https://drive.google.com/open?id=1DLepaCe7ndrqVU3D8x7yjN3TMfhZXSCV

Hello, thanks for your reply. I don't have permission for the datasets on your google cloud disk. Please grant permission, thanks very mush indeed.

**Comment by naoto0804** [comment]
Now it should be viewed by anyone who knows the link above, could you try again?

**Comment by Zxr1314** [comment]
I can access that. Thanks again！

**Comment by pnhaison** [comment]
It worked .Thanks
