### ISSUE TITLE
Some issues about requirements

### ISSUE THREAD

**Issue by tw200464tw** [naoto0804/cross-domain-detection#2]
When I recommended `pip install -r requirements.txt`,an error came out:Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 13)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 13))
     Then.I read the requirement.txt. It was  pkg-resources==0.0.0.
      So is it a clerical error?

**Comment by naoto0804** [comment]
@tw200464tw Thank you for visiting this repository.
Some redundant dependency might be included, is it working if you just remove that line?

**Comment by tw200464tw** [comment]
Yes!  After I remove that line, it was working yesterday.Thank you for the answer.

**Comment by tw200464tw** [comment]
> @tw200464tw Thank you for visiting this repository.
> Some redundant dependency might be included, is it working if you just remove that line?

Yes! After I remove that line, it was working yesterday.Thank you for the answer.

**Comment by naoto0804** [comment]
Thank you for reporting the bug! I've fixed `requirements.txt`.
