### ISSUE TITLE
DT step for train

### ISSUE THREAD

**Issue by dyx118186878** [naoto0804/cross-domain-detection#23]
excuse me ,i use the code to do domain transfer step but i onlt get snapshot file not the model file .is it nomal ,how can i get the dt model.please help me

**Comment by naoto0804** [comment]
If you want to just test the model, this part will automatically load the model appropriately
https://github.com/naoto0804/cross-domain-detection/blob/master/eval_model.py#L29-L30

**Comment by dyx118186878** [comment]
i want to train a new model  should i change the iter num to 10000 or more ?

**Comment by naoto0804** [comment]
Maybe it varies depending on your dataset, so it's difficult to give a fine answer;

**Comment by dyx118186878** [comment]
thanks a lot
