### ISSUE TITLE
The problem of pseudo_label 

### ISSUE THREAD

**Issue by txinp** [naoto0804/cross-domain-detection#24]
excuse me ,I have the following problem when I run pseudo_label , because the path is wrong? And I didn't find the 0001.jpg used in your path.Can you help me with your answer? thank you very much.
(C:\Users\pf\Anaconda3) D:\cross-domain-detection-master>python pseudo_label.py --root datasets/clipart --data_type clipart --det_type ssd300 --gpu 0 --load models/clipart_dt_ssd300 --result datasets/dt_pl_clipart
32 of 500 images, 15.42 FPSTraceback (most recent call last):
  File "pseudo_label.py", line 92, in <module>
    main()
  File "pseudo_label.py", line 82, in main
    labeler = LabelFile(filename, img_path, dataset.actual_labels)
  File "D:\cross-domain-detection-master\lib\label_file.py", line 20, in __init__
    assert(os.path.exists(imagePath))
AssertionError

**Comment by naoto0804** [comment]
I haven't tested it on WIndows.
(i) Could you try `print(imagePath)` and what's the output?
(ii) Could you check if you have downloaded the dataset again?

**Comment by naoto0804** [comment]
Can you see more discussion on #25?
