### ISSUE TITLE
How to train with multi GPU

### ISSUE THREAD

**Issue by LiewFeng** [naoto0804/cross-domain-detection#26]
Hi, I wonder how to train with multi GPU.  When I used three GPU to train, I found that only one GPU was used. My training set is --gpu 2. Looking forward to your reply @naoto0804

**Comment by naoto0804** [comment]
Sorry, there's no plan to support multiple GPUs due to limited time for me. I hope the time for the training is not so long;

**Comment by LiewFeng** [comment]
Thank you for your reply.
