### ISSUE TITLE
Eval only works on first 16 images

### ISSUE THREAD

**Issue by pittyacg** [naoto0804/cross-domain-detection#27]
Hi, when I try to evaluate the models, it finishes after 16 images.

python eval_model.py --root datasets/clipart --data_type clipart --det_type ssd300 --gpu 0 --load models/clipart_dt_pl_ssd300

16 of 500 images, 1.04 FPS
mAP: 45.838514
[0.35795296 0.6231405  0.25748064 0.45363873 0.2972707  0.75524476
 0.46959915 0.02931454 0.5259346  0.72092924 0.5014015  0.19371956
 0.40696306 0.8219697  0.61909188 0.41884568 0.24460997 0.38183322
 0.49152827 0.59723416]

Also, I would like to know how to change the eval function in order to evaluate on the baseline. I know the questions are stupid, but I have never used Chainer.

**Comment by naoto0804** [comment]
Thank you for visiting this repo!

First of all, please make sure that (i) you have fully downloaded the dataset (ii) check each software's version. (this project is done almost two years ago, so I'm not sure it can work on recent version of Chainer or some other dependency libraries)

> it finishes after 16 images.

Could you try `print(len(dataset))` after [here](https://github.com/naoto0804/cross-domain-detection/blob/master/eval_model.py#L38) to diagnose the error?


> Also, I would like to know how to change the eval function in order to evaluate on the baseline

Just drop the `--load` argument. To see what's going on, you can back-track the code from [here](https://github.com/naoto0804/cross-domain-detection/blob/master/eval_model.py#L27). I hope you can finally find that the model trained on VOC07/12 is loaded.

**Comment by pittyacg** [comment]
Thank you for your answer. It seems that the message was wrong. It wasn't 16 images, but batches. 500/32 ~= 16. 

Also, you were right about dropping the load argument.

Thanks!!

**Comment by pittyacg** [comment]
Another quick question.  I can't train the model using faster rcnn. When using SSD everything is fine, but when i change the parameter to faster, I get this error:

![image](https://user-images.githubusercontent.com/10223550/76760312-139c7f00-6796-11ea-99a5-7b59d40bba0e.png)

**Comment by naoto0804** [comment]
Could you pass `--batchsize 1`? (see [here](https://github.com/naoto0804/cross-domain-detection/blob/master/train_model.py#L163))

The Faster R-CNN implementation that I use randomly resizes each input image to a different size for massive data augmentation, while the SSD implementation always resizes each image to a fixed resolution. That makes a difference when you concatenate images to make a batch when the batchsize is larger than 1.

**Comment by pittyacg** [comment]
Thanks, it worked fine liked this. Still, now I can't eval the resulting model. The npz files have different names. Here is the content of the resulting npz file:

![image](https://user-images.githubusercontent.com/10223550/77250247-4b506e80-6c4f-11ea-952c-fc0f0ff011f0.png)

When I run the eval i get: KeyError: 'rpn/loc/b is not a file in the archive'. It seems that in the trained model there are some strings added to the file names.

Thank you!!
