### ISSUE TITLE
I've got a problem installing opencv in requirements

### ISSUE THREAD

**Issue by Heermosi** [naoto0804/cross-domain-detection#31]
I'm working on this in a docker
and I tried, to install the required part from an anaconda pip
where I got this

> 
> Collecting opencv-python==3.4.1.15 (from -r requirements.txt (line 11))                                                                                                         ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.1.15 (from -r requirements.txt (line 11)) (from versions: none)                           ERROR: No matching distribution found for opencv-python==3.4.1.15 (from -r requirements.txt (line 11))
> --
> 
> 
> 

Can I use an alternative to this?

**Comment by Heermosi** [comment]
Solved， I got this report when I typed something like this


> pip install --install-option="--prefix=/workspace/cross-domain-detection" -r requirements.txt
> --
> 

It seems working when I altered to use --target option

**Comment by naoto0804** [comment]
Thank you for your interest in this repo, and glad to hear that you solved the issue!
