### ISSUE TITLE
Installing in docker with cuda 10.1 segmentfault

### ISSUE THREAD

**Issue by Heermosi** [naoto0804/cross-domain-detection#32]
> 
> root@crossdomain:/workspace/cross-domain-detection# python eval_model.py --root  datasets/clipart --data_type clipart --det_type ssd300 --gpu 0 --load models/cli part_dt_pl_ssd300                                                                /opt/conda/lib/python3.6/site-packages/chainercv/links/model/ssd/ssd_vgg16.py:24 5: RuntimeWarning: cv2 is not installed on your environment. Pretrained models a re trained with cv2. The performace may change with Pillow backend.                RuntimeWarning)                                                                Segmentation fault (core dumped)
> --
> 

When I got to build this code, this error interrupted the execution.
Is there any one knew what happened?
Thers is a core dump file 

some supplimentary info:

> Program terminated with signal SIGSEGV, Segmentation fault.                      #0  0x00007fd7073fb75c in elf_machine_rela (skip_ifunc=0,                            reloc_addr_arg=0x7fd6ee5e6f40, version=0x48, sym=0x7fd6ee2db4c0,                 reloc=0x7fd6ee2f0640, map=0x5582cfd5ecb0)                                        at ../sysdeps/x86_64/dl-machine.h:303
> --
> 
> 
> 
Besides
I run the python 

> chainer.cuda.get_device_from_id(0).use()
> --
> 
> 

it works well, but while running in script, it caused a segment fault.
I tried many times, it only works when I append this code just after the import of chainer
What the Hell is it??????

**Comment by naoto0804** [comment]
Hmm, I haven't faced such a problem, although I published this code two years ago and I haven't updated this code up to the latest Chainer version;

I think the problem is maybe common in Chainer, not specific to my code;
I guess the version of Chainer you used is not compatible with cuda10.1??
