### ISSUE TITLE
The pre-trained CycleGAN model

### ISSUE THREAD

**Issue by Liuzhengfa88** [naoto0804/cross-domain-detection#33]
According to the guidelines of the datasets file, we downloaded the "Clipart1k", "PASCAL-VOC",  and "domain-transformed PASCAL-VOC" datasets. However, we couldn't download the "source-transformed Clipart1k" datasets which is generated by the CycleGAN. Can you provide us the pre-trained cyclegan model which maps Clipart1k to source-transformed Clipart1k?

**Comment by naoto0804** [comment]
Sorry, I cannot tell what's "source-transformed Clipart1k", because I only considered VOC -> other datasets adaptation settings.

**Comment by Liuzhengfa88** [comment]
Sorry for my poor explanation.  Briefly, we want to get the pre-trained cyclegan model. Because the cyclegan can translate VOC to other datasets, and in turn, can translate other datasets to VOC. Here, we want to get the pre-trained model trained by VOC and Clipart datasets.

**Comment by Liuzhengfa88** [comment]
> Sorry, I cannot tell what's "source-transformed Clipart1k", because I only considered VOC -> other datasets adaptation settings.

Sorry for my poor explanation. Briefly, we want to get the pre-trained cyclegan model. Because the cyclegan can translate VOC to other datasets, and in turn, can translate other datasets to VOC. Here, we want to get the pre-trained model trained by VOC and Clipart datasets.

**Comment by naoto0804** [comment]
Since it's old, I could not retrieve the exact model. I'd appreciate it if you could train by yourself, sorry;
