### ISSUE TITLE
Issues with prepare_dt.sh script 

### ISSUE THREAD

**Issue by courtneysprouse** [naoto0804/cross-domain-detection#44]
There seems to be an issue with the curl command, maybe the file doesnt exist? Or something changed with the url? It's strange because it was working fine last week and I've curled from a few different ips and getting the same error. I'm also able to run the `prepare.sh` script with no problems

```
curl: (28) Failed to connect to www.hal.t.u-tokyo.ac.jp port 80 after 133021 ms: Couldn't connect to server
unzip:  cannot find or open dt_datasets.zip, dt_datasets.zip.zip or dt_datasets.zip.ZIP.
rm: cannot remove 'dt_datasets.zip': No such file or directory 
```

**Comment by naoto0804** [comment]
Hi, it seems the server is under maintenance. Could you wait for a few days? When the server is back, I'm planning to host the data as the GitHub release later for convenience.

**Comment by courtneysprouse** [comment]
Sure thing! No problem!

**Comment by courtneysprouse** [comment]
Hey just wanted to follow up - I'm still not able to hit the url. Do you have a sense of when the data will be available again?

**Comment by naoto0804** [comment]
Hi, it seems I should migrate the data, and it will take time. Do you need some of the dataset?

**Comment by sparkblame** [comment]
Can you give me a dataset? My email is 1062409423@qq.com

**Comment by naoto0804** [comment]
I have updated the instructions and the links to the dataset on Google Drive. Please pull the latest codes. I'm sorry for not getting back to you sooner.
