### ISSUE TITLE
Original datasets cannot be downloaded

### ISSUE THREAD

**Issue by txllxt123** [naoto0804/cross-domain-detection#45]
I used prepare.sh, but the zips cannot be downloaded. Then I directly accessed the website address in prepare.sh but only 404 not found.

**Comment by gylu22** [comment]
me too!

**Comment by gylu22** [comment]
i have the same problem, Can you send a new link to my account : ilgyulze@gmail.com, really appreciate！

**Comment by naoto0804** [comment]
I have updated the instructions and the links to the dataset on Google Drive. Please pull the latest codes. I'm sorry for not getting back to you sooner.

**Comment by fengjingchehu** [comment]
Have you obtained the dataset yet? If you have and could send a new link to my email, I would greatly appreciate it. xincunduicuo@gmail.com

**Comment by naoto0804** [comment]
Hi, @fengjingchehu, Could you follow these instructions?
https://github.com/naoto0804/cross-domain-detection/blob/master/datasets/README.md
