### ISSUE TITLE
NameError: name 'apply_prediction_to_iterator' is not defined

### ISSUE THREAD

**Issue by cool-xuan** [naoto0804/cross-domain-detection#5]
I can't find a function define in ChianerCV.But your code use this function in eval_model.py.Please tell me how to deeal with it.

**Comment by naoto0804** [comment]
Thank you for bug reporting and your interest in this repo!
After I published the code, the name of the function is changed. ([reference](https://github.com/chainer/chainercv/pull/523))
Please rename the function or just use `chainercv==0.8.0`.
