### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by shayxurui** [naoto0804/cross-domain-detection#6]
FileNotFoundError: [Errno 2] No such file or directory:'datasets/dt_clipart/VOC2012/ImageSets/Main/test.txt‘

when i train Domain transfer (DT) step,
python train_model.py --root datasets/dt_clipart/VOC2007 --root datasets/dt_clipart/VOC2012 --subset train --result result/dt_clipart --det_type ssd300 --data_type clipart --gpu 0 --max_iter 500

**Comment by naoto0804** [comment]
I'm afraid you just forget the rest of the args. It seems that `--load models/clipart_dt_ssd300 --eval_root datasets/clipart` is missing. Could you try again?

**Comment by naoto0804** [comment]
Please refer to #7
