### ISSUE TITLE
ImportError: No module named lib.label_file

### ISSUE THREAD

**Issue by Mickeybaby** [naoto0804/cross-domain-detection#8]
python pseudo_label.py
ImportError: No module named lib.label_file

**Comment by naoto0804** [comment]
It would be nice if you report the system information you use.
I'm afraid you are using Python2.

### System information
- **Have I written custom code**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **CUDA/cuDNN version**:
- **Exact command to reproduce**:

**Comment by zwyyy215** [comment]
Yes, I use 2.7. Thank you for your help.
